version: '3'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  web:
    build: .
    command: rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/test-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  postgres-volume:
